name: tremor_ml
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - ipython
  - tsfresh
  - numpy<=1.21  # To fix "Numba needs NumPy 1.21 or less" TSFRESH ImportError
  - obspy
  - pip
  - pygmt
  - scikit-learn
  - jupyter
