name: tremor_ml
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - numpy
  - obspy
  - pygmt
  - scikit-learn
  - colorcet
  - libcomcat  
  - pip
  - pip:
      - git+https://github.com/uafgeotools/waveform_collection.git
