name: voiss-net
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipython
  - numpy
  - obspy
  - geopy
  - pygmt
  - scikit-learn
  - colorcet
  - seaborn
  - libcomcat  
  - tensorflow
  - opencv
  - pip
  - pip:
      - label-studio
      - ordpy
      - git+https://github.com/uafgeotools/waveform_collection.git
